name: flutter_coverage_badge
description: Flutter Coverage Badge
version: 0.0.1+1
author: Minsu Lee <amond@amond.net>
homepage: https://github.com/amondnet/flutter_coverage_badge

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
executables:
  flutter_coverage_badge:

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  glob: ^2.0.1
  args: ^2.1.0
  lcov:
    git:
      url: https://github.com/amondnet/lcov.dart.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
